#========MenShearSnow========#
#  	       @7kasper  	     #
#========MenShearSnow========#

#You can edit all of this to give the plugin a different name, command, etc,
#just make sure the syntax stays the same.

name: MenShearSnow
main: nl.kasper7.bukkit.MenShearSnow.MenShearSnow
version: 0.1.0
author: 7kasper
depend: [ProtocolLib]